name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.6.0

    # - name: Cache Flutter dependencies
    #   uses: actions/cache@v1
    #   with:
    #     path: /opt/hostedtoolcache/flutter
    #     key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    - name: Install Flutter
      uses: subosito/flutter-action@v2.10.0
      with:
        channel: 'stable' 
    
    - name: Get dependencies
      run: flutter pub get
    
    # - name: Analyze project
    #   run: flutter analyze

    # - name: Test project
    #   run: flutter test
    
    - name: Build release project
      run: flutter build web --base-href "/IIITB_Menu/"

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v3.1.2
      with:
        name: production-files
        path: ./build/web
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3.1.12
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
